# Generated by Django 3.2.12 on 2022-05-18 12:31

from django.db import migrations, models
import pik.core.models.uided


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIKMessageException',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('uid', models.UUIDField(default=pik.core.models.uided._new_uid, editable=False, primary_key=True, serialize=False)),
                ('entity_uid', models.UUIDField(blank=True, null=True, verbose_name='Идентификатор сущности')),
                ('queue', models.CharField(max_length=255, verbose_name='Очередь')),
                ('message', models.BinaryField(verbose_name='Сообщение')),
                ('exception', models.JSONField(verbose_name='Ошибка')),
                ('exception_type', models.CharField(verbose_name='Тип ошибки', max_length=255)),
                ('exception_message', models.CharField(verbose_name='Сообщение об ошибке', max_length=255)),
                ('dependencies', models.JSONField(verbose_name='Зависимости', blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Сообщение шины',
                'verbose_name_plural': 'Сообщения шины',
            },
        ),
    ]
